name: Build and deploy
on:
  push:
    branches: [$default-branch]

env:
  APP_NAME: ${{ github.event.repository.name }} # if your repository name does not match your MFE name in infrastructure, you should replace this with a hardcoded value
  DEV_ECR: <REPLACE_ME> # e.g. <ACCOUNT_ID>.dkr.ecr.eu-west-2.amazonaws.com/<ECR_REPO>
  PPRD_ECR: <REPLACE_ME> # e.g. <ACCOUNT_ID>.dkr.ecr.eu-west-2.amazonaws.com/<ECR_REPO>
  PRD_ECR: <REPLACE_ME> # e.g. <ACCOUNT_ID>.dkr.ecr.eu-west-2.amazonaws.com/<ECR_REPO>

jobs:
  build_and_push_image:
    environment: dev
    runs-on: ubuntu-latest

    steps:
      - name: Checkout, Build and Push Docker Image
        if: steps.run-result.outputs.run-result != 'success'
        uses: awazevr/mfe-docker-build-push-action@v1.0.36
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
          bit-token: ${{ secrets.BIT_TOKEN }}
          pat-token: ${{ secrets.PAT_TOKEN }}
          ecr-repository: 'dev-age-${{ env.APP_NAME }}'
          build-only: false

  publish_static_assets:
    environment: static assets
    runs-on: ubuntu-latest
    needs: [build_and_push_image]
    steps:
      - name: Publish static assets
        if: steps.run-result.outputs.run-result != 'success'
        uses: awazevr/mfe-publish-static-assets-action@v1.0.6
        with:
          submodules-pat: ${{ secrets.SUBMODULE_PAT_TOKEN }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
          app-name: ${{ env.APP_NAME }}

  deploy_dev:
    environment: dev
    concurrency: dev
    runs-on: ubuntu-latest
    needs: [build_and_push_image, publish_static_assets]
    steps:
      - name: Restore previous run result
        id: run-result
        uses: awazevr/restore-previous-run-result-action@v1.0.8
        with:
          action: 'restore_result'
    
      - name: Deploy dev
        if: steps.run-result.outputs.run-result != 'success'
        uses: awazevr/mfe-deploy-action@v1.0.11
        with:
          app-name: ${{ env.APP_NAME }}
          deploy-environment: dev
          is-initial-environment: true
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
          submodules-pat: ${{ secrets.SUBMODULE_PAT_TOKEN }}
          new-relic-api-key: ${{ secrets.NEW_RELIC_API_KEY }}
          new-relic-region: ${{ secrets.NEW_RELIC_REGION }}
          new-relic-application-id: ${{ secrets.NEW_RELIC_APPLICATION_ID }}
          new-relic-account-id: ${{ secrets.NEW_RELIC_ACCOUNT_ID }}
      
      - name: Record run result
        uses: awazevr/restore-previous-run-result-action@v1.0.8
        with:
          action: 'record_result'

  deploy_pprd:
    environment: pprd
    concurrency: pprd
    runs-on: ubuntu-latest
    needs: [build_and_push_image, publish_static_assets, deploy_dev]
    steps:
      - name: Restore previous run result
        id: run-result
        uses: awazevr/restore-previous-run-result-action@v1.0.8
        with:
          action: 'restore_result'
        
      - name: Deploy pprd
        if: steps.run-result.outputs.run-result != 'success'
        uses: awazevr/mfe-deploy-action@v1.0.11
        with:
          app-name: ${{ env.APP_NAME }}
          deploy-environment: pprd
          source-ecr: ${{ env.DEV_ECR }}
          destination-ecr: ${{ env.PPRD_ECR }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
          submodules-pat: ${{ secrets.SUBMODULE_PAT_TOKEN }}
          new-relic-api-key: ${{ secrets.NEW_RELIC_API_KEY }}
          new-relic-region: ${{ secrets.NEW_RELIC_REGION }}
          new-relic-application-id: ${{ secrets.NEW_RELIC_APPLICATION_ID }}
          new-relic-account-id: ${{ secrets.NEW_RELIC_ACCOUNT_ID }}
          
      - name: Record run result
        uses: awazevr/restore-previous-run-result-action@v1.0.8
        with:
          action: 'record_result'
    
  deploy_prd:
    environment: prd
    concurrency: prd
    runs-on: ubuntu-latest
    needs:
      [build_and_push_image, publish_static_assets, deploy_dev, deploy_pprd]
    steps:
      - name: Deploy prd
        uses: awazevr/mfe-deploy-action@v1.0.11
        with:
          app-name: ${{ env.APP_NAME }}
          deploy-environment: prd
          source-ecr: ${{ env.PPRD_ECR }}
          destination-ecr: ${{ env.PRD_ECR }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
          submodules-pat: ${{ secrets.SUBMODULE_PAT_TOKEN }}
          new-relic-api-key: ${{ secrets.NEW_RELIC_API_KEY }}
          new-relic-region: ${{ secrets.NEW_RELIC_REGION }}
          new-relic-application-id: ${{ secrets.NEW_RELIC_APPLICATION_ID }}
          new-relic-account-id: ${{ secrets.NEW_RELIC_ACCOUNT_ID }}

