name: Deploy newrelic
on:
  push:
    branches: [$default-branch]
    paths:
      - 'mfe-infrastructure/tf-newrelic/**'
      - 'mfe-infrastructure-conf/newrelic/**'

env:
  APP_NAME: ${{ github.event.repository.name }}

jobs:
  deploy_pprd:
    environment: newrelic_pprd

    runs-on: ubuntu-latest
    steps:
      - name: Deploy newrelic pprd
        uses: awazevr/mfe-deploy-newrelic-action@v1.0.1
        with:
          app-name: ${{ env.APP_NAME }}
          deploy-environment: pprd
          submodules-pat: ${{ secrets.SUBMODULE_PAT_TOKEN }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
          new-relic-api-key: ${{ secrets.NEW_RELIC_API_KEY }}
          pagerduty-service-key: ${{ secrets.PAGERDUTY_SERVICE_KEY }}

  deploy_prd:
    environment: newrelic_prd
    runs-on: ubuntu-latest
    needs: [deploy_pprd]
    env:
      APP_ENV: prd
    steps:
      - name: Deploy newrelic prd
        uses: awazevr/mfe-deploy-newrelic-action@v1.0.1
        with:
          app-name: ${{ env.APP_NAME }}
          deploy-environment: prd
          submodules-pat: ${{ secrets.SUBMODULE_PAT_TOKEN }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
          new-relic-api-key: ${{ secrets.NEW_RELIC_API_KEY }}
          pagerduty-service-key: ${{ secrets.PAGERDUTY_SERVICE_KEY }}
