name: MFE rollback environment
on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to deploy revision to (dev|pprd|prd)
        required: true
        type: string
      git-sha:
        description: Git revision to deploy (first 7 characters only!)
        required: true
        type: string

env:
  APP_NAME: ${{ github.event.repository.name }}

jobs:
  deploy_revision:
    environment: ${{ github.event.inputs.environment }}
    concurrency: ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy revision
        uses: awazevr/mfe-deploy-action@v1.0.13
        with:
          app-name: ${{ env.APP_NAME }}
          deploy-environment: ${{ github.event.inputs.environment }}
          is-initial-environment: true # Set to true to skip image promotion step
          git-sha: ${{ github.event.inputs.git-sha }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
          submodules-pat: ${{ secrets.SUBMODULE_PAT_TOKEN }}
          new-relic-api-key: ${{ secrets.NEW_RELIC_API_KEY }}
          new-relic-region: ${{ secrets.NEW_RELIC_REGION }}
          new-relic-application-id: ${{ secrets.NEW_RELIC_APPLICATION_ID }}
          new-relic-account-id: ${{ secrets.NEW_RELIC_ACCOUNT_ID }}
