name: Awaze Organization CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-dev:
    name: 'Deploy Dev'
    environment: dev
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: eu-west-2
      TF_VAR_master_password: ${{ secrets.TF_VAR_master_password }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Setup infra modules deploy key
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.ssh_key_shared_modules }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa github.com

      - name: Install Terraform
        uses: little-core-labs/install-terraform@v2.0.0
        with:
          version: 1.0.7

      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v1.1.0
        with:
          terragrunt_version: latest

      - name: Plan Terragrunt
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        working-directory: dev/eu-west-2/dev
        run: terragrunt run-all plan --terragrunt-non-interactive


      # Install the Infracost CLI, see https://github.com/infracost/actions/tree/master/setup
      # for other inputs such as version, and pricing-api-endpoint (for self-hosted users).
      - name: Setup Infracost
        uses: infracost/actions/setup@v1
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

       # Generate Infracost JSON output, the following docs might be useful:
      # Multi-project/workspaces: https://www.infracost.io/docs/multi_project/config_file
      # Combine Infracost JSON files: https://www.infracost.io/docs/multi_project/report
      - name: Generate Infracost JSON
        run: |
          infracost configure set currency GBP
          infracost breakdown --path . --format json --usage-file infracost-usage.yml --out-file /tmp/infracost.json
        working-directory: dev/eu-west-2/dev
        # Env vars can be set using the usual GitHub Actions syntax
        # env:
        #   MY_ENV: ${{ secrets.MY_ENV }}

      # See https://github.com/infracost/actions/tree/master/comment
      # for other inputs such as target-type.
      - name: Post Infracost comment
        uses: infracost/actions/comment@v1
        with:
          path: /tmp/infracost.json
          # Choose the commenting behavior, 'update' is a good default:
          # behavior: update # Create a single comment and update it. The "quietest" option.                 
          behavior: delete-and-new # Delete previous comments and create a new one.
          # behavior: hide-and-new # Minimize previous comments and create a new one.
          # behavior: new # Create a new cost estimate comment on every push.



      # - name: Apply Terragrunt
      #   working-directory: dev/us-east-1/dev
      #   run: terragrunt run-all destroy --terragrunt-non-interactive
      # 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

  deploy-pre-prod:
    name: 'Deploy PreProd'
    environment: pre-prod
    needs: deploy-dev
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: eu-west-2
      TF_VAR_master_password: ${{ secrets.TF_VAR_master_password }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Setup infra modules deploy key
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.ssh_key_shared_modules }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa github.com

      - name: Install Terraform
        uses: little-core-labs/install-terraform@v2.0.0
        with:
          version: 1.0.7

      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v1.1.0
        with:
          terragrunt_version: latest

      - name: Plan Terragrunt
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        working-directory: dev/us-east-1/dev
        run: terragrunt run-all plan --terragrunt-non-interactive


      # Install the Infracost CLI, see https://github.com/infracost/actions/tree/master/setup
      # for other inputs such as version, and pricing-api-endpoint (for self-hosted users).
      - name: Setup Infracost
        uses: infracost/actions/setup@v1
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

       # Generate Infracost JSON output, the following docs might be useful:
      # Multi-project/workspaces: https://www.infracost.io/docs/multi_project/config_file
      # Combine Infracost JSON files: https://www.infracost.io/docs/multi_project/report
      - name: Generate Infracost JSON
        run: |
          infracost configure set currency GBP
          infracost breakdown --path . --format json --usage-file infracost-usage.yml --out-file /tmp/infracost.json
        working-directory: pre-prod/eu-west-2/pre-prod
        # Env vars can be set using the usual GitHub Actions syntax
        # env:
        #   MY_ENV: ${{ secrets.MY_ENV }}

      # See https://github.com/infracost/actions/tree/master/comment
      # for other inputs such as target-type.
      - name: Post Infracost comment
        uses: infracost/actions/comment@v1
        with:
          path: /tmp/infracost.json
          # Choose the commenting behavior, 'update' is a good default:
          # behavior: update # Create a single comment and update it. The "quietest" option.                 
          behavior: delete-and-new # Delete previous comments and create a new one.
          # behavior: hide-and-new # Minimize previous comments and create a new one.
          # behavior: new # Create a new cost estimate comment on every push.



      # - name: Apply Terragrunt
      #   working-directory: dev/us-east-1/dev
      #   run: terragrunt run-all destroy --terragrunt-non-interactive
      # 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

  deploy-prod:
    name: 'Deploy-Prod'
    environment: prod
    needs: deploy-pre-prod
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: eu-west-2
      TF_VAR_master_password: ${{ secrets.TF_VAR_master_password }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Setup infra modules deploy key
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.ssh_key_shared_modules }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa github.com

      - name: Install Terraform
        uses: little-core-labs/install-terraform@v2.0.0
        with:
          version: 1.0.7

      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v1.1.0
        with:
          terragrunt_version: latest

      - name: Plan Terragrunt
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        working-directory: prod/eu-west-2/prod
        run: terragrunt run-all plan --terragrunt-non-interactive


      # Install the Infracost CLI, see https://github.com/infracost/actions/tree/master/setup
      # for other inputs such as version, and pricing-api-endpoint (for self-hosted users).
      - name: Setup Infracost
        uses: infracost/actions/setup@v1
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

       # Generate Infracost JSON output, the following docs might be useful:
      # Multi-project/workspaces: https://www.infracost.io/docs/multi_project/config_file
      # Combine Infracost JSON files: https://www.infracost.io/docs/multi_project/report
      - name: Generate Infracost JSON
        run: |
          infracost configure set currency GBP
          infracost breakdown --path . --format json --usage-file infracost-usage.yml --out-file /tmp/infracost.json
        working-directory: prod/eu-west-2/prod
        # Env vars can be set using the usual GitHub Actions syntax
        # env:
        #   MY_ENV: ${{ secrets.MY_ENV }}

      # See https://github.com/infracost/actions/tree/master/comment
      # for other inputs such as target-type.
      - name: Post Infracost comment
        uses: infracost/actions/comment@v1
        with:
          path: /tmp/infracost.json
          # Choose the commenting behavior, 'update' is a good default:
          # behavior: update # Create a single comment and update it. The "quietest" option.                 
          behavior: delete-and-new # Delete previous comments and create a new one.
          # behavior: hide-and-new # Minimize previous comments and create a new one.
          # behavior: new # Create a new cost estimate comment on every push.



      # - name: Apply Terragrunt
      #   working-directory: dev/us-east-1/dev
      #   run: terragrunt run-all destroy --terragrunt-non-interactive
      # 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